// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwJIxIZM4JiLszxIrmNL9ySu0xLMTzy3k',
    appId: '1:635921452897:web:5d6b188de0eef20854ff20',
    messagingSenderId: '635921452897',
    projectId: 'snifferpettracker',
    authDomain: 'snifferpettracker.firebaseapp.com',
    storageBucket: 'snifferpettracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNinyfn__zvfurgZDYZsUj9VhC3ZzVZ84',
    appId: '1:635921452897:android:5df050a5eaa9011d54ff20',
    messagingSenderId: '635921452897',
    projectId: 'snifferpettracker',
    storageBucket: 'snifferpettracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDslgyR930qiBc5aCj0AsY_WLqb5r3mcr8',
    appId: '1:635921452897:ios:0c1400114254030854ff20',
    messagingSenderId: '635921452897',
    projectId: 'snifferpettracker',
    storageBucket: 'snifferpettracker.appspot.com',
    iosClientId: '635921452897-v09f4ogae748s76ufi2eio1mp18q672b.apps.googleusercontent.com',
    iosBundleId: 'com.example.snifferPettrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDslgyR930qiBc5aCj0AsY_WLqb5r3mcr8',
    appId: '1:635921452897:ios:0c1400114254030854ff20',
    messagingSenderId: '635921452897',
    projectId: 'snifferpettracker',
    storageBucket: 'snifferpettracker.appspot.com',
    iosClientId: '635921452897-v09f4ogae748s76ufi2eio1mp18q672b.apps.googleusercontent.com',
    iosBundleId: 'com.example.snifferPettrackingApp',
  );
}
